sudo: false

language: node_js

node_js:
  - 6.10.0

cache:
  directories:
    - node_modules

install:
  - npm set progress=false
  - npm install

branches:
  only:
    - master
    - prod
    - stage

script:
  - npm run config
  - npm run lint:fix
  # - npm run test
  - npm run build:prod

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    project: $TRAVIS_BRANCH
    secure: $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
