sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - ./build/dist.sh
  - npm run lint
  - npm run test
  - NODE_ENV=production npm run deploy

after_success:
  - npm run codecov

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU
  app: devshare-stg
